# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='valeur')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='unité')),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='objectif')),
                ('trend', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='tendance (%)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculé le')),
                ('period', models.CharField(choices=[('DAILY', 'Journalier'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel')], default='MONTHLY', max_length=20, verbose_name='période')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyStockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('reserved_quantity', models.IntegerField(verbose_name='quantité réservée')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='prix unitaire')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valeur totale')),
                ('movements_in', models.IntegerField(default=0, verbose_name='entrées')),
                ('movements_out', models.IntegerField(default=0, verbose_name='sorties')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='products.product', verbose_name='produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='warehouses.warehouse', verbose_name='entrepôt')),
            ],
            options={
                'verbose_name': 'snapshot stock',
                'verbose_name_plural': 'snapshots stock',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_ac6c25_idx'), models.Index(fields=['product', '-date'], name='analytics_d_product_dcdc37_idx')],
                'unique_together': {('date', 'product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('year', models.IntegerField(verbose_name='année')),
                ('month', models.IntegerField(verbose_name='mois')),
                ('quantity_consumed', models.IntegerField(verbose_name='quantité consommée')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='coût total')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_consumption', to='departments.department', verbose_name='département')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_consumption', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'consommation mensuelle',
                'verbose_name_plural': 'consommations mensuelles',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month', 'product', 'department')},
            },
        ),
    ]
