# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succès'), ('STOCK_LOW', 'Stock bas'), ('STOCK_OUT', 'Rupture de stock'), ('ORDER_RECEIVED', 'Commande reçue'), ('ORDER_SHIPPED', 'Commande expédiée'), ('INVENTORY_DUE', 'Inventaire à faire'), ('MAINTENANCE_DUE', 'Maintenance à faire'), ('ANOMALY', 'Anomalie détectée')], default='INFO', max_length=30, verbose_name='type')),
                ('channel', models.CharField(choices=[('IN_APP', "Dans l'application"), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], default='IN_APP', max_length=20, verbose_name='canal')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.URLField(blank=True, verbose_name='lien')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('is_sent', models.BooleanField(default=True, verbose_name='envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('priority', models.IntegerField(default=0, verbose_name='priorité')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='type objet lié')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='ID objet lié')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
