# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('original_id', models.UUIDField(unique=True)),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'archive log audit',
                'verbose_name_plural': 'archives logs audit',
                'ordering': ['-archive_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('user_email', models.CharField(blank=True, help_text="Email de l'utilisateur au moment de l'action", max_length=254, verbose_name='email utilisateur')),
                ('user_role', models.CharField(blank=True, max_length=50, verbose_name='rôle utilisateur')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('VIEW', 'Consultation'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='action')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], default='INFO', max_length=20, verbose_name='sévérité')),
                ('module', models.CharField(max_length=100, verbose_name='module')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('content_type', models.CharField(blank=True, help_text="Modèle concerné (ex: 'products.Product')", max_length=100, verbose_name='type de contenu')),
                ('object_id', models.CharField(blank=True, help_text="UUID ou clé primaire de l'objet", max_length=100, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='représentation objet')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Valeurs avant modification', verbose_name='anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='Valeurs après modification', verbose_name='nouvelles valeurs')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Diff entre anciennes et nouvelles valeurs', verbose_name='changements')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='méthode HTTP')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='chemin requête')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='statut réponse')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='durée (ms)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "log d'audit",
                'verbose_name_plural': "logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs__user_id_c41764_idx'), models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['module'], name='audit_logs__module_77713d_idx'), models.Index(fields=['severity'], name='audit_logs__severit_e57ae8_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs__content_dc4f20_idx'), models.Index(fields=['-created_at'], name='audit_logs__created_cc00f5_idx')],
            },
        ),
    ]
