# Generated by Django 6.0.6 on 2026-06-20 02:03

import apps.attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('object_id', models.UUIDField(verbose_name='ID objet')),
                ('file', models.FileField(max_length=500, upload_to=apps.attachments.models.attachment_upload_path, verbose_name='fichier')),
                ('filename', models.CharField(max_length=500, verbose_name='nom du fichier')),
                ('file_size', models.BigIntegerField(verbose_name='taille (octets)')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('SPREADSHEET', 'Tableur'), ('ARCHIVE', 'Archive'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='type de fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='type MIME')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='somme de contrôle SHA256')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('download_count', models.IntegerField(default=0, verbose_name='téléchargements')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='téléchargé par')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx'), models.Index(fields=['uploaded_by'], name='attachments_uploade_220573_idx')],
            },
        ),
    ]
