# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('type', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('PREDICTIVE', 'Prédictive'), ('CALIBRATION', 'Calibration'), ('INSPECTION', 'Inspection')], default='PREVENTIVE', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('OVERDUE', 'En retard')], default='SCHEDULED', max_length=20, verbose_name='statut')),
                ('description', models.TextField(verbose_name='description du problème')),
                ('actions_taken', models.TextField(blank=True, verbose_name='actions effectuées')),
                ('scheduled_date', models.DateTimeField(verbose_name='date planifiée')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='coût')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='durée (minutes)')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='pièces remplacées')),
                ('next_maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='prochaine maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='products.product', verbose_name='produit/équipement')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='technicien')),
            ],
            options={
                'verbose_name': 'maintenance',
                'verbose_name_plural': 'maintenances',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['product', '-scheduled_date'], name='maintenance_product_454213_idx'), models.Index(fields=['status'], name='maintenance_status_4bd260_idx'), models.Index(fields=['next_maintenance_date'], name='maintenance_next_ma_7a099a_idx')],
            },
        ),
    ]
