# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('ORDERED', 'Commandée'), ('PARTIALLY_RECEIVED', 'Reçue partiellement'), ('RECEIVED', 'Reçue'), ('CANCELLED', 'Annulée'), ('REJECTED', 'Rejetée')], default='DRAFT', max_length=30, verbose_name='statut')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='date de commande')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='date de livraison prévue')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='date de livraison réelle')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='montant total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='TVA')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='frais de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='purchase_orders/%Y/%m/', verbose_name='pièce jointe')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='approuvé par')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_orders', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'bon de commande',
                'verbose_name_plural': 'bons de commande',
                'ordering': ['-order_date'],
                'permissions': [('approve_order', 'Peut approuver une commande')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix total')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='quantité reçue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='products.product', verbose_name='produit')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_orders.purchaseorder', verbose_name='bon de commande')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'unique_together': {('purchase_order', 'product')},
            },
        ),
    ]
