# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('APPROVED', 'Approuvée'), ('PROCESSING', 'En cours'), ('DELIVERED', 'Livrée'), ('PARTIALLY_DELIVERED', 'Partiellement livrée'), ('CANCELLED', 'Annulée'), ('REJECTED', 'Rejetée')], default='DRAFT', max_length=30, verbose_name='statut')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='priorité')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='livré le')),
                ('justification', models.TextField(blank=True, verbose_name='justification')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('total_items', models.IntegerField(default=0, verbose_name="nombre d'articles")),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='approuvé par')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='departments.department', verbose_name='département')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='warehouses.warehouse', verbose_name='entrepôt')),
            ],
            options={
                'verbose_name': 'demande interne',
                'verbose_name_plural': 'demandes internes',
                'ordering': ['-created_at'],
                'permissions': [('approve_request', 'Peut approuver une demande')],
            },
        ),
        migrations.CreateModel(
            name='InternalRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('quantity', models.IntegerField(verbose_name='quantité demandée')),
                ('delivered_quantity', models.IntegerField(default=0, verbose_name='quantité livrée')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix unitaire estimé')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='products.product', verbose_name='produit')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requests.internalrequest', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'ligne de demande',
                'verbose_name_plural': 'lignes de demande',
                'unique_together': {('request', 'product')},
            },
        ),
    ]
