# Generated by Django 6.0.6 on 2026-06-20 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='numéro contribuable')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='numéro registre commerce')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('BLACKLISTED', 'Liste noire'), ('PENDING', 'En attente')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='catégorie')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='personne contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='pays')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='banque')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='compte bancaire')),
                ('bank_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='conditions de paiement')),
                ('delivery_time_days', models.IntegerField(default=7, verbose_name='délai de livraison (jours)')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='commande minimum')),
                ('rating', models.IntegerField(default=0, verbose_name='évaluation')),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='contrat')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'), models.Index(fields=['status'], name='suppliers_s_status_e60785_idx')],
            },
        ),
    ]
