# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('type', models.CharField(choices=[('FULL', 'Complet'), ('PARTIAL', 'Partiel'), ('CYCLE', 'Tournant'), ('SPOT', 'Ponctuel')], default='FULL', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('VALIDATED', 'Validé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=20, verbose_name='statut')),
                ('start_date', models.DateTimeField(verbose_name='date début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date fin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('expected_items', models.IntegerField(default=0, verbose_name='articles attendus')),
                ('counted_items', models.IntegerField(default=0, verbose_name='articles comptés')),
                ('differences', models.IntegerField(default=0, verbose_name='écarts')),
                ('total_value_expected', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valeur attendue')),
                ('total_value_counted', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valeur comptée')),
                ('value_difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='écart de valeur')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_inventories', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_inventories', to=settings.AUTH_USER_MODEL, verbose_name='superviseur')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouses.warehouse', verbose_name='entrepôt')),
            ],
            options={
                'verbose_name': 'inventaire',
                'verbose_name_plural': 'inventaires',
                'ordering': ['-start_date'],
                'permissions': [('validate_inventory', 'Peut valider un inventaire')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('expected_quantity', models.IntegerField(verbose_name='quantité attendue')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, verbose_name='quantité comptée')),
                ('difference', models.IntegerField(default=0, verbose_name='écart')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix unitaire')),
                ('difference_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valeur écart')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='compté le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='compté par')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventories.inventory', verbose_name='inventaire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': "ligne d'inventaire",
                'verbose_name_plural': "lignes d'inventaire",
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
