# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text='Contenu encodé dans le QR code', max_length=255, unique=True, verbose_name='code QR')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/', verbose_name='image QR code')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier scan')),
                ('scan_count', models.IntegerField(default=0, verbose_name='nombre de scans')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='appareil')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='localisation')),
                ('action', models.CharField(blank=True, help_text='Action déclenchée par le scan', max_length=50, verbose_name='action')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qr_codes.qrcode', verbose_name='QR code')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='scanné par')),
            ],
            options={
                'verbose_name': 'log de scan',
                'verbose_name_plural': 'logs de scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='code-barres')),
                ('format', models.CharField(choices=[('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC'), ('QR', 'QR Code')], default='CODE128', max_length=20, verbose_name='format')),
                ('image', models.ImageField(blank=True, null=True, upload_to='barcodes/%Y/%m/', verbose_name='image code-barres')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'code-barres',
                'verbose_name_plural': 'codes-barres',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['code'], name='qr_codes_ba_code_970df3_idx'), models.Index(fields=['product', 'is_primary'], name='qr_codes_ba_product_a4f477_idx')],
            },
        ),
    ]
