# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantité')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='quantité réservée')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='quantité disponible')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix unitaire')),
                ('location', models.CharField(blank=True, help_text='Rayon, étagère, etc.', max_length=100, verbose_name='emplacement')),
                ('last_inventory_date', models.DateTimeField(blank=True, null=True, verbose_name='dernier inventaire')),
                ('last_movement_date', models.DateTimeField(blank=True, null=True, verbose_name='dernier mouvement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouses.warehouse', verbose_name='entrepôt')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ['warehouse', 'product__category', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrée'), ('OUTPUT', 'Sortie'), ('TRANSFER', 'Transfert'), ('ADJUSTMENT', 'Ajustement'), ('RETURN', 'Retour')], max_length=20, verbose_name='type de mouvement')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Achat'), ('SALE', 'Vente'), ('INTERNAL_USE', 'Usage interne'), ('DONATION', 'Don'), ('DAMAGE', 'Dommage'), ('LOSS', 'Perte'), ('RETURN_SUPPLIER', 'Retour fournisseur'), ('INVENTORY_ADJUSTMENT', 'Ajustement inventaire'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name='raison')),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix total')),
                ('reference_document', models.CharField(blank=True, max_length=100, verbose_name='document de référence')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('is_validated', models.BooleanField(default=False, verbose_name='validé')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_movements', to=settings.AUTH_USER_MODEL, verbose_name='effectué par')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_movements.stock', verbose_name='stock')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_movements', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-created_at'],
                'permissions': [('validate_movement', 'Peut valider un mouvement'), ('cancel_movement', 'Peut annuler un mouvement')],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='stock_movem_product_7e58f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_movem_quantit_e1e6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_movement_date'], name='stock_movem_last_mo_537be2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock', '-created_at'], name='stock_movem_stock_i_332fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_0168dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='stock_movem_created_55bd3f_idx'),
        ),
    ]
