# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('reason', models.CharField(choices=[('INTERNAL_USE', 'Usage interne'), ('TRANSFER', 'Transfert'), ('DAMAGE', 'Dommage'), ('EXPIRED', 'Expiré'), ('LOSS', 'Perte'), ('RETURN', 'Retour fournisseur'), ('OTHER', 'Autre')], default='INTERNAL_USE', max_length=20, verbose_name='motif')),
                ('recipient', models.CharField(blank=True, max_length=200, verbose_name='bénéficiaire')),
                ('output_date', models.DateTimeField(auto_now_add=True, verbose_name='date de sortie')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='montant total')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outputs', to='departments.department', verbose_name='département bénéficiaire')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_outputs', to=settings.AUTH_USER_MODEL, verbose_name='remis par')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_outputs', to=settings.AUTH_USER_MODEL, verbose_name='reçu par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_outputs', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outputs', to='warehouses.warehouse', verbose_name='entrepôt')),
            ],
            options={
                'verbose_name': 'sortie de stock',
                'verbose_name_plural': 'sorties de stock',
                'ordering': ['-output_date'],
            },
        ),
        migrations.CreateModel(
            name='StockOutputLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix total')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='emplacement')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_outputs.stockoutput', verbose_name='sortie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_lines', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'ligne de sortie',
                'verbose_name_plural': 'lignes de sortie',
            },
        ),
    ]
