# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('name', models.CharField(max_length=300, verbose_name='nom')),
                ('report_type', models.CharField(choices=[('STOCK_LEVEL', 'Niveau de stock'), ('MOVEMENT', 'Mouvements'), ('CONSUMPTION', 'Consommation'), ('INVENTORY', 'Inventaire'), ('PURCHASE', 'Achats'), ('FINANCIAL', 'Financier'), ('CUSTOM', 'Personnalisé')], max_length=20, verbose_name='type de rapport')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('WORD', 'Word')], default='PDF', max_length=10, verbose_name='format')),
                ('frequency', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel')], default='MONTHLY', max_length=20, verbose_name='fréquence')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Jour 0'), (1, 'Jour 1'), (2, 'Jour 2'), (3, 'Jour 3'), (4, 'Jour 4'), (5, 'Jour 5'), (6, 'Jour 6')], null=True, verbose_name='jour de la semaine')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='jour du mois')),
                ('time', models.TimeField(verbose_name='heure')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='destinataires')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='paramètres')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='dernière génération')),
                ('next_generation', models.DateTimeField(blank=True, null=True, verbose_name='prochaine génération')),
            ],
            options={
                'verbose_name': 'planification rapport',
                'verbose_name_plural': 'planifications rapport',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('name', models.CharField(max_length=300, verbose_name='nom')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('type', models.CharField(choices=[('STOCK_LEVEL', 'Niveau de stock'), ('MOVEMENT', 'Mouvements'), ('CONSUMPTION', 'Consommation'), ('INVENTORY', 'Inventaire'), ('PURCHASE', 'Achats'), ('FINANCIAL', 'Financier'), ('CUSTOM', 'Personnalisé')], default='STOCK_LEVEL', max_length=20, verbose_name='type')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('WORD', 'Word')], default='PDF', max_length=10, verbose_name='format')),
                ('status', models.CharField(choices=[('GENERATING', 'En génération'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='GENERATING', max_length=20, verbose_name='statut')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='fichier')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='paramètres')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtres')),
                ('data_summary', models.JSONField(blank=True, default=dict, verbose_name='résumé données')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='taille fichier')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', '-created_at'], name='reports_rep_type_a9e508_idx'), models.Index(fields=['generated_by', '-created_at'], name='reports_rep_generat_ef0442_idx')],
            },
        ),
    ]
