# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('type', models.CharField(choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secondaire'), ('MOBILE', 'Mobile'), ('VIRTUAL', 'Virtuel')], default='SECONDARY', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('MAINTENANCE', 'En maintenance'), ('CLOSED', 'Fermé')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='capacité (m²)')),
                ('is_temperature_controlled', models.BooleanField(default=False, verbose_name='température contrôlée')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='température min (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='température max (°C)')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name="heures d'ouverture")),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='campuses.campus', verbose_name='campus')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='departments.department', verbose_name='département')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='gestionnaire')),
            ],
            options={
                'verbose_name': 'entrepôt',
                'verbose_name_plural': 'entrepôts',
                'ordering': ['campus', 'name'],
                'permissions': [('manage_warehouse', "Peut gérer l'entrepôt"), ('view_warehouse_stock', "Peut voir le stock de l'entrepôt")],
            },
        ),
    ]
