# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('name', models.CharField(max_length=300)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('BOX', 'Boîte'), ('KG', 'Kilogramme'), ('LITER', 'Litre'), ('METER', 'Mètre'), ('PACK', 'Pack'), ('SET', 'Ensemble')], default='PIECE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('DISCONTINUED', 'Abandonné')], default='ACTIVE', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('min_stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('optimal_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['reference'], name='products_pr_referen_d05358_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx')],
            },
        ),
    ]
