# Generated by Django 6.0.6 on 2026-06-20 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('to_email', models.EmailField(max_length=254, verbose_name='destinataire')),
                ('subject', models.CharField(max_length=500, verbose_name='sujet')),
                ('body', models.TextField(blank=True, verbose_name='corps')),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('BOUNCED', 'Rebondi'), ('OPENED', 'Ouvert')], default='SENT', max_length=20, verbose_name='statut')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
            ],
            options={
                'verbose_name': 'log email',
                'verbose_name_plural': 'logs email',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('subject_template', models.CharField(help_text='Utilise {{ variable }} pour les placeholders', max_length=500, verbose_name='template sujet')),
                ('body_template', models.TextField(help_text='Template HTML ou texte', verbose_name='template corps')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'template notification',
                'verbose_name_plural': 'templates notification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('key', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='clé')),
                ('value', models.TextField(blank=True, verbose_name='valeur')),
                ('value_type', models.CharField(choices=[('string', 'Texte'), ('integer', 'Entier'), ('float', 'Décimal'), ('boolean', 'Booléen'), ('json', 'JSON')], default='string', max_length=20, verbose_name='type de valeur')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('category', models.CharField(default='general', max_length=100, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'paramètre système',
                'verbose_name_plural': 'paramètres système',
                'ordering': ['category', 'key'],
            },
        ),
    ]
