# Generated by Django 6.0.6 on 2026-06-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('IN_TRANSIT', 'En transit'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='expédié le')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='reçu le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('total_items', models.IntegerField(default=0, verbose_name="nombre total d'articles")),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='approuvé par')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouses.warehouse', verbose_name='entrepôt destination')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouses.warehouse', verbose_name='entrepôt source')),
            ],
            options={
                'verbose_name': 'transfert',
                'verbose_name_plural': 'transferts',
                'ordering': ['-created_at'],
                'permissions': [('approve_transfer', 'Peut approuver un transfert'), ('ship_transfer', 'Peut expédier un transfert'), ('receive_transfer', 'Peut recevoir un transfert')],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID v4 unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when the object was soft deleted', null=True)),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='prix total')),
                ('source_location', models.CharField(blank=True, max_length=100, verbose_name='emplacement source')),
                ('destination_location', models.CharField(blank=True, max_length=100, verbose_name='emplacement destination')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='products.product', verbose_name='produit')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transfer', verbose_name='transfert')),
            ],
            options={
                'verbose_name': 'ligne de transfert',
                'verbose_name_plural': 'lignes de transfert',
                'unique_together': {('transfer', 'product')},
            },
        ),
    ]
